[[plugins]]
repo = 'zchee/deoplete-clang'
on_ft = ['c', 'cpp']

[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = 'python'

[[plugins]]
repo = 'zchee/deoplete-go'
build = 'make'
on_i = 1
on_ft = 'go'


[[plugins]]
repo = 'Shougo/deoplete.nvim'
depends = 'context_filetype.vim'
if = "has('nvim')"
on_i = 1
hook_source = '''
  let g:deoplete#enable_at_startup = 1
  source ~/.vim/rc/plugins/deoplete.rc.vim
'''


[[plugins]]
repo = 'Shougo/Denite.nvim'
on_cmd = 'Denite'
hook_add = '''
  nnoremap [denite] <Nop>
  nmap <Leader> [denite]
  nnoremap [denite]a :Denite file_rec<CR>
  nnoremap [denite]f :Denite file_mru<CR>
  nnoremap [denite]l :Denite line<CR>
  nnoremap [denite]g :Denite grep<CR>
'''
hook_source = '''
     call denite#custom#var('file_rec', 'command',
          \ ['ag', '--follow', '--nocolor', '--nogroup', '-g', ''])

    call denite#custom#source(
          \ 'file_mru', 'matchers', ['matcher_fuzzy', 'matcher_project_files'])

    call denite#custom#map('_', "\<C-j>", 'move_to_next_line')
    call denite#custom#map('_', "\<C-k>", 'move_to_prev_line')
'''
