[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'



[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = 'source ~/.vim/rc/plugins/lightline.rc.vim'

[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = '''
  let g:indentLine_faster = 1
  let g:indentLine_enabled = 1
'''

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

#[[plugins]]
#repo = 'christoomey/vim-tmux-navigator'

[[plugins]]
repo = 'Shougo/unite-build'

[[plugins]]
repo = 'tyru/open-browser.vim'
on_map = [['n', '<Plug>']]


##[[plugins]]
##repo = 'scrooloose/syntastic'


# Html
[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = ['html', 'html5', 'php', 'xml', 'css']


[[plugins]]
repo = 'othree/html5.vim'
on_ft = ['html', 'html5', 'php', 'xml', 'css']


# MarkDown
[[plugins]]
repo = 'godlygeek/tabular'
on_ft = 'markdown'

[[plugins]]
repo = 'joker1007/vim-markdown-quote-syntax'
on_ft = 'markdown'

[[plugins]]
repo = 'rcmdnk/vim-markdown'
on_ft = 'markdown'



[[plugins]]
repo = 'hynek/vim-python-pep8-indent'
on_ft = 'python'



[[plugins]]
repo = 'jmcantrell/vim-virtualenv'
on_ft = 'python'



[[plugins]]
repo = 'zaiste/tmux.vim'
on_ft = 'tmux'

[[plugins]]
repo = 'smancill/conky-syntax.vim'
on_ft = '*.conkyrc'

[[plugins]]
repo = 'lilydjwg/colorizer'
on_ft = ['css', 'vim']
on_path = ['*.tmux.conf', '*.zshrc', '*.xmonad.hs', '*.xmobarrc', '*.Xdefault']


[[plugins]]
repo = 'pasela/unite-webcolorname'
on_ft = ['css', 'vim']
on_path = ['*.tmux.conf', '*.zshrc', '*.xmonad.hs', '*.xmobarrc', '*.Xdefault']

[[plugins]]
repo = 'vim-jp/vim-cpp'
on_ft = 'cpp'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'jelera/vim-javascript-syntax'

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'


[[plugins]]
repo = 'elzr/vim-json'
on_ft = 'json'

[[plugins]]
repo = 'osyo-manga/shabadou.vim'

[[plugins]]
repo = 'osyo-manga/unite-quickfix'


[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'kana/vim-operator-user'


[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = 'Shougo/context_filetype.vim'


[[plugins]]
repo = 'thinca/vim-template'
hook_add =  '''
    autocmd MyAutoCmd User plugin-template-loaded call s:template_keywords()
    function! s:template_keywords()
        silent! %s/<+DATE+>/\=strftime('%Y-%m-%d')/g
        silent! %s/<+FILENAME+>/\=expand('%:r')/g
    endfunction
    autocmd MyAutoCmd User plugin-template-loaded
        \   if search('<+CURSOR+>')
        \ |    silent! execute 'normal! "_da>'
        \ | endif
'''

#[[plugins]]
#repo = 'rhysd/nyaovim-markdown-preview'

[[plugins]]
repo = 'mattn/emoji-vim'
