[brew]
tap = ["homebrew/bundle", "homebrew/cask", "homebrew/services"]
cask = ["appcleaner", "mactex", "the-unarchiver", "xquartz"]
pkgs = [
    "autoconf",
    "bazel",
    "cmake", "coreutils", "ctags",
    "direnv", "diff-so-fancy",
    "ffmpeg", "fish", "fontconfig", "fontforge",
    "gawk", "git", "glib", "glide", "graphviz",
    "hub",
    "imagemagick",
    "jq",
    "lame",
    "mariadb", "mecab", "mecab-ipadic",
    "neovim", "nkf", "nmap",
    "opencv3", "open-jtalk", "openssl",
    "pkg-config", "protobuf",
    "qt",
    "rbenv", "readline", "reattach-to-user-namespace",
    "ruby-build",
    "shelcheck", "sqlite", "swig",
    "terminal-notifier", "tmux",
    "w3m", "wget","zsh-completions",
]

[[brew.optionalPkgs]]
    pkg = "htop"
    args = ["--with-ncurses"]

[[brew.optionalPkgs]]
    pkg = "llvm"
    args = ["--with-clang"]

[[brew.optionalPkgs]]
    pkg = "zsh"
    args = ["--disable-etcdir"]

[go]
[[go.pkgs]]
    repo = "k-hosokawa/powerline-go"
[[go.pkgs]]
    repo = "motemen/ghq"
[[go.pkgs]]
    repo = "peco/peco"
[[go.pkgs]]
    repo = "mattn/memo"
[[go.pkgs]]
    repo = "k-hosokawa/gov"
[[go.pkgs]]
    repo = "junegunn/fzf"
[[go.pkgs]]
    repo = "b4b4r07/history"
    onZshComp = "misc/zsh/completions"
    onZshSource = "misc/zsh/init.zsh"

[rust]
repos = [
    "exa",
    "fd",
    "ripgrep",
]

[src]
[[src.pkg]]
repo = "b4b4r07/zsh-vimode-visual"
onZshSource = "zsh-vimode-visual.zsh"

[[src.pkg]]
repo = "zsh-users/zsh-completions"
onZshComp = "src"

[[src.pkg]]
repo = "zsh-users/zsh-syntax-highlighting"
onZshSource = "zsh-syntax-highlighting.zsh"

[[src.pkg]]
repo = "b4b4r07/enhancd"
onZshSource = "init.sh"

[[src.pkg]]
repo = "Valodim/zsh-curl-completion"
onZshComp = "."

[[src.pkg]]
repo = "b4b4r07/zsh-gomi"
onCmd = "bin/gomi"
onZshComp = "src"

[[src.pkg]]
repo = "b4b4r07/emoji-cli"
onZshSource = "emoji-cli.zsh"

[[src.pkg]]
repo = "mrowa44/emojify"
onCmd = "emojify"

[[src.pkg]]
repo = "simonwhitaker/gibo"
onCmd = "gibo"

[[src.pkg]]
repo = "Fakerr/git-recall"
onCmd = "git-recall"

[[src.pkg]]
repo = "jwilm/alacritty"
onOs = "darwin"
build = [
    "make app",
]
onApp = "target/release/osx/Alacritty.app"

[[src.pkg]]
repo = "b4b4r07/peco-tmux.sh"
onCmd = "peco-tmux.sh"
renameTo = "peco-tmux"

[[src.pkg]]
repo = "k-hosokawa/pyv"
build = ["make"]
buildEnv = ["PREFIX=__PAC_HOME__"]

[[src.pkg]]
repo = "hokaccha/nodebrew"
onCmd = "nodebrew"
build = [
    "wget git.io/nodebrew",
    "perl nodebrew setup",
]

[[src.pkg]]
repo = "direnv/direnv"
build = ["make", "make install"]
buildEnv = ["DESTDIR=__PAC_HOME__"]


