hook_add = '''
" Python
let g:python_highlight_all = 1
let python_highlight_all = 1

" Tex
let g:tex_flavor = 'latex'
let g:tex_fold_enabled = 1
'''


[ftplugin]
_ = '''
  " Disable automatically insert comment.
  setl formatoptions-=ro | setl formatoptions+=mMBl
'''
python = '''
  highlight pythonSelf ctermfg=61 guifg=#5f5faf
  syn keyword pythonSelf self
  highlight pythonLogger ctermfg=125 guifg=#af005f
  match pythonLogger /\<logger\>/
'''

go = '''
  highlight default link goErr WarningMsg
  match goErr /\<err\>/
'''
