hook_add = '''
" Tex
let g:tex_flavor = 'latex'
let g:tex_fold_enabled = 1

'''


[ftplugin]

_ = '''
" Disable automatically insert comment.
setl formatoptions-=ro
setl formatoptions+=mMBl

if &filetype !=# 'help'
  setl foldtext=FoldCCtext()
endif
if !&l:modifiable
  setl nofoldenable
  setl foldcolumn=0
  setl colorcolumn=
endif
'''

c_cpp = '''
setl expandtab
setl tabstop=4
setl shiftwidth=2
setl softtabstop=2
setl commentstring=//%s
'''

python = '''
setl expandtab
setl tabstop=4
setl shiftwidth=4
setl softtabstop=4
let g:__python_read_test__ = "b"
"syn match pythonOperator "\(+\|=\|-\|\^\|\*\|<\|>\|\)"
"hi link pythonOperator Special

'''

go = '''
setl noexpandtab
setl tabstop=4
setl shiftwidth=4
setl softtabstop=4
setl commentstring=//%s

highlight default link goErr WarningMsg
match goErr /\<err\>/
'''
javascript = '''
setl expandtab
setl tabstop=2
setl shiftwidth=2
setl softtabstop=2
'''

make = '''
setl expandtab
setl noexpandtab
setl tabstop=8
setl shiftwidth=8
setl softtabstop=8
'''

vim = '''
setl expandtab
setl tabstop=2
setl shiftwidth=2
setl softtabstop=2
'''

vue = '''
setl expandtab
setl tabstop=2
setl shiftwidth=2
setl softtabstop=2
setl commentstring=//%s
'''

zsh = '''
setl expandtab
setl tabstop=2
setl softtabstop=2
setl shiftwidth=2
'''

sh = '''
setl expandtab
setl tabstop=2
setl softtabstop=2
setl shiftwidth=2
'''
