#!/usr/bin/env python
# _*_ coding: utf-8 _*_

# Created: 2017-06-07
import os
import sys

import numpy as np


if __name__ == "__main__":
    path = sys.argv[1]
    path = os.path.expanduser(path)
    npy = np.load(path)
    print("shape:", npy.shape)
    print("dtype", npy.dtype)


# vim:set fenc=utf-8 ff=unix expandtab sw=4 ts=4:
